/**
 * @file project_info.hpp
 * @brief Declares access to pdi-labs build and dependency metadata.
 */

#pragma once

#include <string_view>

namespace pdi::core {

/**
 * @brief Provides immutable metadata about the configured pdi-labs project.
 *
 * @details The methods expose values generated by CMake and OpenCV during
 * configuration and compilation. Every returned view refers to a string with
 * static storage duration, so the class does not allocate memory and does not
 * transfer ownership.
 *
 * @note This class is intentionally small and serves as the first complete
 * example of the Doxygen documentation conventions adopted by the project.
 *
 * @see project_name()
 * @see project_version()
 * @see opencv_version()
 */
class ProjectInfo {
public:
    /**
     * @brief Returns the CMake project name.
     *
     * @return Project name with static storage duration.
     *
     * @post The returned view remains valid for the entire process lifetime.
     */
    [[nodiscard]] static std::string_view project_name() noexcept;

    /**
     * @brief Returns the configured semantic version.
     *
     * @return Project version with static storage duration.
     *
     * @post The returned view remains valid for the entire process lifetime.
     */
    [[nodiscard]] static std::string_view project_version() noexcept;

    /**
     * @brief Returns the OpenCV version used during compilation.
     *
     * @return OpenCV version with static storage duration.
     *
     * @post The returned view remains valid for the entire process lifetime.
     */
    [[nodiscard]] static std::string_view opencv_version() noexcept;
};

} // namespace pdi::core
