/**
 * @file m1_1_pipeline.hpp
 * @brief Declares the integrated Laboratory M1.1 pipeline.
 */

#pragma once

#include <filesystem>
#include <vector>

#include <opencv2/core/mat.hpp>

#include "pdi/io/image_display.hpp"

namespace pdi::labs {

/**
 * @brief Stores all images generated by the integrated M1.1 pipeline.
 */
struct M11Results {
    cv::Mat input;
    cv::Mat manual_copy;
    cv::Mat blue_channel;
    cv::Mat green_channel;
    cv::Mat red_channel;
    cv::Mat grayscale_average;
    cv::Mat grayscale_weighted;
    cv::Mat quantized_16;
    cv::Mat quantized_8;
    cv::Mat quantized_4;
    cv::Mat quantized_2;
};

/**
 * @brief Integrates all processing components developed for Laboratory M1.1.
 *
 * @details The pipeline loads one color image, produces every required result,
 * persists them through `pdi::io`, and writes a CSV inspection report.
 * Quantization is applied to the weighted grayscale image.
 */
class M11Pipeline {
public:
    /**
     * @brief Executes the complete Laboratory M1.1 workflow.
     *
     * @param input_path Input image path.
     * @param output_directory Directory where outputs will be written.
     * @return All generated images for optional display or validation.
     *
     * @throws std::runtime_error If input loading or output persistence fails.
     * @throws std::invalid_argument If an internal precondition is violated.
     */
    [[nodiscard]] M11Results run(
        const std::filesystem::path& input_path,
        const std::filesystem::path& output_directory
    ) const;

    /**
     * @brief Creates the named image collection used by the `--show` option.
     *
     * @param results Complete pipeline results.
     * @return Ordered images with unambiguous window titles.
     */
    [[nodiscard]] std::vector<pdi::io::WindowImage> display_images(
        const M11Results& results
    ) const;
};

} // namespace pdi::labs
